nextflow run main.nf\
 -profile tartu_hpc\
 --readPathsFile data/readPathsFile_macrophages_PE.tsv\
 --reverse_stranded\
 --hisat2_index /gpfs/hpc/projects/genomic_references/annotations/eQTLCatalogue/v0.1/hisat2_index_v96/Homo_sapiens.GRCh38.dna.primary_assembly\
 --aligner 'hisat2'\
 --skip_qc\
 --skip_multiqc\
 --skip_stringtie\
 --saveReference\
 --run_tx_exp_quant\
 --run_splicing_exp_quant\
 --run_exon_quant\
 --saveTrimmed\
 --saveAlignedIntermediates\
 --gtf /gpfs/hpc/projects/genomic_references/annotations/eQTLCatalogue/v0.1/gencode.v30.annotation.no_chr.gtf\
 --fasta /gpfs/hpc/projects/genomic_references/annotations/eQTLCatalogue/v0.1/Homo_sapiens.GRCh38.dna.primary_assembly.fa\
 --tx_fasta /gpfs/hpc/projects/genomic_references/annotations/eQTLCatalogue/v0.1/gencode.v30.transcripts.fa\
 -resume
